### ISSUE TITLE
Error when running step 2

### ISSUE THREAD

**Issue by htdepot** [marksgraham/DW-POSSUM#10]
/usr/local/fsl/bin/fsl_sub -T 20 -l /data/jht/DW-POSSUM-master/Test/Direction0/logs  -M jht@fmrib.ox.ac.uk -N possum -t /data/jht/DW-POSSUM-master/Test/Direction0/possum.com
Error submitting job - Errors occured when running array task in shell plugin: Task 1 failed executing: /usr/local/fsl/bin/possum -i /data/jht/DW-POSSUM-master/Test/Direction0/brain -x /data/jht/DW-POSSUM-master/Test/Direction0/MRpar -f /data/jht/DW-POSSUM-master/Test/Direction0/slcprof -p /data/jht/DW-POSSUM-master/Test/Direction0/pulse -m /data/jht/DW-POSSUM-master/Test/Direction0/motion --nproc=1 -e /data/jht/DW-POSSUM-master/Test/Direction0/matrix --procid=0 -o /data/jht/DW-POSSUM-master/Test/Direction0/diff_proc/signal_proc_0 (Image Exception : #22 :: Failed to read volume /data/jht/DW-POSSUM-master/Test/Direction0/brain
Error : Error: ROI out of bounds for /data/jht/DW-POSSUM-master/Test/Direction0/brain.nii.gz
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to read volume /data/jht/DW-POSSUM-master/Test/Direction0/brain
Error : Error: ROI out of bounds for /data/jht/DW-POSSUM-master/Test/Direction0/brain.nii.gz
)

/usr/local/fsl/bin/fsl_sub -T 10 -j  -F -l /data/jht/DW-POSSUM-master/Test/Direction0/logs  /usr/local/fsl/bin/possumX_postproc.sh /data/jht/DW-POSSUM-master/Test/Direction0 1
usage: fsl_sub [-h] [-a ARCH] [-c COPROCESSOR]
               [--coprocessor_multi COPROCESSOR_MULTI]
               [--coprocessor_class COPROCESSOR_CLASS]
               [--coprocessor_class_strict]
               [--coprocessor_toolkit COPROCESSOR_TOOLKIT] [-F] [-j JOBHOLD]
               [--not_requeueable] [--array_hold ARRAY_HOLD] [-l LOGDIR]
               [-m MAILOPTIONS] [-M MAILTO] [-n] [-N NAME] [-p PRIORITY]
               [-q QUEUE] [-r RESOURCE] [--delete_job DELETE_JOB]
               [--extra EXTRA] [-R GB] [-s PARALLELENV,THREADS]
               [-t ARRAY_TASK] [--array_native ARRAY_NATIVE] [-x NUMBER]
               [--keep_jobscript] [--has_coprocessor COPROCESSOR_NAME]
               [--has_queues] [--project PROJECT] [-S] [-T MINUTES]
               [--show_config] [-v] [-V] [-z file]
               ...
fsl_sub: error: argument -j/--jobhold: expected one argument

**Comment by marksgraham** [comment]
Are you using FSL 5.0.10? It has only been tested with this version

**Comment by htdepot** [comment]
> Are you using FSL 5.0.10? It has only been tested with this version

Thanks for your reply, I didn't notice the FSL version requirement, that's why this went wrong, I'm using FSL 6.0.6.

**Comment by AdairMaldonado** [comment]
Hi, Could someone help me to get the fslinstaller.py for fsl version 5.10?
I just got to know POSSUM, but it doesn't run with FSL 6 and I can't find the old files

**Comment by marksgraham** [comment]
Does this link help? 
https://web.mit.edu/fsl_v5.0.10/fsl/doc/wiki/FslInstallation.html
I think you can install 5.0.0 and then patch to 5.10

If that helps might be worth asking on the FSL forums https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=fsl

**Comment by AdairMaldonado** [comment]
Thank you for you response, I tried to post to the forum, but I had trouble creating my account.
Unfortunately when I enter the fslinstaller.py file from the link it directs me to the updated FSL-6.0.6, I also have another question, I am using a Mac with an M1 chip that is, arm64. Is it possible to run FSL 5 on this machine if I install XQuartz?

**Comment by marksgraham** [comment]
Hi,

I'm afraid I don't know the answer to that - again probably a question best addressed at the FLS devs, sorry!

**Comment by AdairMaldonado** [comment]
Don't worry, Thank you for your time. Have a good day.
