### ISSUE TITLE
What is the relationship between noise_levels and SNR in step 3

### ISSUE THREAD

**Issue by htdepot** [marksgraham/DW-POSSUM#11]
./postProcess.py Test 3 --noise_levels 0 0.0081 0.0165
For example, what is the SNR corresponding to 0.0081

**Comment by marksgraham** [comment]
I've always done it empirically by generating the noise and then measuring the SNR on the resulting images.

**Comment by htdepot** [comment]
> I've always done it empirically by generating the noise and then measuring the SNR on the resulting images.

Thank you for your reply!
