### ISSUE TITLE
excuse me , I want to know how to simulate the artefacts MRI data?

### ISSUE THREAD

**Issue by strawberry1996** [marksgraham/DW-POSSUM#3]
excuse me , I want to know how to simulate the artefacts MRI data?

**Comment by marksgraham** [comment]
Hi there, 
What artefacts are you interested in including? There are some example motion files in Files/Motion/. If you interested in susceptibility fields you need to include such a field in the simulation folder - some info on that can be found here https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/POSSUM/UserGuide#B0_inhomogeneities.
Eddy currents requires modifying the pulse sequence itself - I can send you some examples if thats what you're interested in.
