### ISSUE TITLE
Error running step 3 - postprocess

### ISSUE THREAD

**Issue by snapfinger** [marksgraham/DW-POSSUM#4]
Hi there, I can run the first two steps without problems, however when it comes to the last step it gives the following error message and I didn't see any generated files under directory /Test/Results
➜  DW-POSSUM git:(master) ✗ ./postProcess.py Test 3 --noise_levels 0 0.0081 0.0165
[0.0, 0.0081, 0.0165]
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction0/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image0
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image0
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction0/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image0
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image0
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction0/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image0
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image0
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction1/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image1
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image1
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction1/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image1
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image1
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction1/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image1
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image1
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction2/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image2
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image2
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction2/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image2
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image2
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds
mv: cannot stat '/hd2/EE591/project/DW-POSSUM/Test/Direction2/imageNoise_abs.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image2
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image2
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image0
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image0
Aborted (core dumped)
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image0.nii.gz': No such file or directory
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image1.nii.gz': No such file or directory
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0_image2.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image0
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image0
Aborted (core dumped)
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image0.nii.gz': No such file or directory
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image1.nii.gz': No such file or directory
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0081_image2.nii.gz': No such file or directory
Image Exception : #63 :: No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image0
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image0
Aborted (core dumped)
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image0.nii.gz': No such file or directory
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image1.nii.gz': No such file or directory
rm: cannot remove '/hd2/EE591/project/DW-POSSUM/Test/Results/diff_sigma0.0165_image2.nii.gz': No such file or directory

**Comment by snapfinger** [comment]
Digging a bit deeper, it seems the [signal2image](https://github.com/marksgraham/DW-POSSUM/blob/00cf938f296f4904b07a79f7fb530378c62650c8/postProcess.py#L137) line causes the following error which leads the other errors.

```
nx,ny,nz 72 86 1 
dx,dy,dz 2.5 2.5 2.5 
Reshaping the signal...

error: Mat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::operator(): index out of bounds

```


btw. I'm using fsl 6.0.0

**Comment by marksgraham** [comment]
What version of FSL are you using?

**Comment by snapfinger** [comment]
As I mentioned in the last thread, it's fsl 6.0.0. Should I upgrade to 6.0.1? My machine is a Ubuntu 16.04 LTS.

**Comment by marksgraham** [comment]
Could you try running a simple POSSUM simulation: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/POSSUM
If that doesn't work then it looks like the problem is with FSL itself.

**Comment by snapfinger** [comment]
Thanks, I tried it, and indeed, it looks it's even having problem with generating `signal`. If use `readsignal` function in your code, it will just output empty list.

```
/usr/local/fsl/bin/fsl_sub -T 10 -j 12457 -F -l /hd2/EE591/project/DW-POSSUM/simdir/logs  /usr/local/fsl/bin/possumX_postproc.sh /hd2/EE591/project/DW-POSSUM/simdir 5
/usr/local/fsl/bin/possum_sum -i /hd2/EE591/project/DW-POSSUM/simdir/diff_proc/signal_proc_ -o /hd2/EE591/project/DW-POSSUM/simdir/signal -n 5
Could not open matrix file /hd2/EE591/project/DW-POSSUM/simdir/diff_proc/signal_proc_0
Could not open matrix file /hd2/EE591/project/DW-POSSUM/simdir/diff_proc/signal_proc_1
Could not open matrix file /hd2/EE591/project/DW-POSSUM/simdir/diff_proc/signal_proc_2
Could not open matrix file /hd2/EE591/project/DW-POSSUM/simdir/diff_proc/signal_proc_3
Could not open matrix file /hd2/EE591/project/DW-POSSUM/simdir/diff_proc/signal_proc_4
Sat Apr  6 09:52:12 PDT 2019
/usr/local/fsl/bin/signal2image -i /hd2/EE591/project/DW-POSSUM/simdir/signal -o /hd2/EE591/project/DW-POSSUM/simdir/image -p /hd2/EE591/project/DW-POSSUM/simdir/pulse -a --homo
nx,ny,nz 64 64 1
dx,dy,dz 4 4 1
Reshaping the signal...

error: Mat::operator(): index out of bounds
```

Do you have any suggestions for resolving this issue?
I wonder which version of FSL you were using (including the operating system)?

**Comment by marksgraham** [comment]
I've been using FSL 5.0.9 and python 2.7 with:
dipy (0.12.0)
nibabel (2.1.0)
numpy (1.13.1)
scipy (0.19.0)

Mark

**Comment by snapfinger** [comment]
Thanks. Indeed, running with FSL ver. 5.0.8 (didn't find 5.0.9) in macOS is without problem.

**Comment by 15thai** [comment]
Hi there, 
I also have the same problem, is there any way we can fix this using fsl6.0?
Since I don't know how to downgrade into fsl5.0 to run a quick tutorial. Thank you.
