### ISSUE TITLE
spikes in epi pulse sequence

### ISSUE THREAD

**Issue by snapfinger** [marksgraham/DW-POSSUM#5]
Hi Mark, when I visualize the EPI pulse sequence used for DWI simulation included in your `Files`, I saw there're spikes at the beginning and end of all three gradients (Gx, Gy and Gz), I wonder how should I interpret those spikes? For the front ones I guess they are to move to the initial k-space starting point? Which is understandable. But how about the end ones?

From some textbooks it seems there should not be such spikes, so how would these affect simulation results?

![image](https://user-images.githubusercontent.com/13393457/56553363-20dbca00-6543-11e9-8681-ce933411d153.png)

**Comment by marksgraham** [comment]
Hi. You're right about the initial spikes being used to navigate to the correct start in k-space. The spikes at the end of the sequence are gradient crushers, used to remove any remaining longitudinal magnetisation before the next RF pulse. You can read about it more here: http://mriquestions.com/spoiling---what-and-how.html

**Comment by snapfinger** [comment]
Got it, thanks!
