### ISSUE TITLE
index and acparam of simulated DWI for input of eddy

### ISSUE THREAD

**Issue by iverson333** [marksgraham/DW-POSSUM#6]
Hi, I'm trying to use simulated dwi published in https://www.nitrc.org/projects/diffusionsim/ which is said to be generated by DW-possum for experiments with FSL eddy's outlier detection function. There're two parameters required by eddy, `index `and `acparam` specifying information about phase encoding. What should I input to eddy if I use this simulated DWI? Or does it matter what's the content of these two files if I'm only interested in eddy's outlier detection function?

**Comment by marksgraham** [comment]
Hi there,

If you're only interested in eddy's outlier detection than acqp values
aren't important. They only matter if you want to be able to interpret the
off-resonance field that eddy outputs in Hz- more info here:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/Faq#Does_it_matter_what_I_put_into_my_--acqp_file.3F
.

So f you're using the motion datasets from NITRC, which all have the same
PE direction (y), then you just need one line in your acqp, e.g.

0 1 0 0.1

and your index file should just be a series of 1s.

Mark

**Comment by iverson333** [comment]
Thank you!
